// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/infer_server.proto

package detectron_infer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Point struct {
	X                    int32    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Point) Reset()         { *m = Point{} }
func (m *Point) String() string { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()    {}
func (*Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_infer_server_0eb42ce3bc0a4c21, []int{0}
}
func (m *Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Point.Unmarshal(m, b)
}
func (m *Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Point.Marshal(b, m, deterministic)
}
func (dst *Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Point.Merge(dst, src)
}
func (m *Point) XXX_Size() int {
	return xxx_messageInfo_Point.Size(m)
}
func (m *Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Point proto.InternalMessageInfo

func (m *Point) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Point) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type Context struct {
	UserData             map[string]string `protobuf:"bytes,1,rep,name=user_data,json=userData,proto3" json:"user_data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	OptionParams         map[string]string `protobuf:"bytes,2,rep,name=option_params,json=optionParams,proto3" json:"option_params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Context) Reset()         { *m = Context{} }
func (m *Context) String() string { return proto.CompactTextString(m) }
func (*Context) ProtoMessage()    {}
func (*Context) Descriptor() ([]byte, []int) {
	return fileDescriptor_infer_server_0eb42ce3bc0a4c21, []int{1}
}
func (m *Context) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Context.Unmarshal(m, b)
}
func (m *Context) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Context.Marshal(b, m, deterministic)
}
func (dst *Context) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Context.Merge(dst, src)
}
func (m *Context) XXX_Size() int {
	return xxx_messageInfo_Context.Size(m)
}
func (m *Context) XXX_DiscardUnknown() {
	xxx_messageInfo_Context.DiscardUnknown(m)
}

var xxx_messageInfo_Context proto.InternalMessageInfo

func (m *Context) GetUserData() map[string]string {
	if m != nil {
		return m.UserData
	}
	return nil
}

func (m *Context) GetOptionParams() map[string]string {
	if m != nil {
		return m.OptionParams
	}
	return nil
}

type Classification struct {
	Class                string   `protobuf:"bytes,1,opt,name=class,proto3" json:"class,omitempty"`
	Confidence           float32  `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Classification) Reset()         { *m = Classification{} }
func (m *Classification) String() string { return proto.CompactTextString(m) }
func (*Classification) ProtoMessage()    {}
func (*Classification) Descriptor() ([]byte, []int) {
	return fileDescriptor_infer_server_0eb42ce3bc0a4c21, []int{2}
}
func (m *Classification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Classification.Unmarshal(m, b)
}
func (m *Classification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Classification.Marshal(b, m, deterministic)
}
func (dst *Classification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Classification.Merge(dst, src)
}
func (m *Classification) XXX_Size() int {
	return xxx_messageInfo_Classification.Size(m)
}
func (m *Classification) XXX_DiscardUnknown() {
	xxx_messageInfo_Classification.DiscardUnknown(m)
}

var xxx_messageInfo_Classification proto.InternalMessageInfo

func (m *Classification) GetClass() string {
	if m != nil {
		return m.Class
	}
	return ""
}

func (m *Classification) GetConfidence() float32 {
	if m != nil {
		return m.Confidence
	}
	return 0
}

type RequestData struct {
	Base64               string   `protobuf:"bytes,1,opt,name=base64,proto3" json:"base64,omitempty"`
	Raw                  []byte   `protobuf:"bytes,2,opt,name=raw,proto3" json:"raw,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestData) Reset()         { *m = RequestData{} }
func (m *RequestData) String() string { return proto.CompactTextString(m) }
func (*RequestData) ProtoMessage()    {}
func (*RequestData) Descriptor() ([]byte, []int) {
	return fileDescriptor_infer_server_0eb42ce3bc0a4c21, []int{3}
}
func (m *RequestData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestData.Unmarshal(m, b)
}
func (m *RequestData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestData.Marshal(b, m, deterministic)
}
func (dst *RequestData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestData.Merge(dst, src)
}
func (m *RequestData) XXX_Size() int {
	return xxx_messageInfo_RequestData.Size(m)
}
func (m *RequestData) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestData.DiscardUnknown(m)
}

var xxx_messageInfo_RequestData proto.InternalMessageInfo

func (m *RequestData) GetBase64() string {
	if m != nil {
		return m.Base64
	}
	return ""
}

func (m *RequestData) GetRaw() []byte {
	if m != nil {
		return m.Raw
	}
	return nil
}

type DetectRequest struct {
	Context              *Context     `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Data                 *RequestData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *DetectRequest) Reset()         { *m = DetectRequest{} }
func (m *DetectRequest) String() string { return proto.CompactTextString(m) }
func (*DetectRequest) ProtoMessage()    {}
func (*DetectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_infer_server_0eb42ce3bc0a4c21, []int{4}
}
func (m *DetectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetectRequest.Unmarshal(m, b)
}
func (m *DetectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetectRequest.Marshal(b, m, deterministic)
}
func (dst *DetectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetectRequest.Merge(dst, src)
}
func (m *DetectRequest) XXX_Size() int {
	return xxx_messageInfo_DetectRequest.Size(m)
}
func (m *DetectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DetectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DetectRequest proto.InternalMessageInfo

func (m *DetectRequest) GetContext() *Context {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *DetectRequest) GetData() *RequestData {
	if m != nil {
		return m.Data
	}
	return nil
}

type BBox struct {
	LeftTop              *Point   `protobuf:"bytes,1,opt,name=left_top,json=leftTop,proto3" json:"left_top,omitempty"`
	RightBottom          *Point   `protobuf:"bytes,2,opt,name=right_bottom,json=rightBottom,proto3" json:"right_bottom,omitempty"`
	Confidence           float32  `protobuf:"fixed32,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BBox) Reset()         { *m = BBox{} }
func (m *BBox) String() string { return proto.CompactTextString(m) }
func (*BBox) ProtoMessage()    {}
func (*BBox) Descriptor() ([]byte, []int) {
	return fileDescriptor_infer_server_0eb42ce3bc0a4c21, []int{5}
}
func (m *BBox) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BBox.Unmarshal(m, b)
}
func (m *BBox) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BBox.Marshal(b, m, deterministic)
}
func (dst *BBox) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BBox.Merge(dst, src)
}
func (m *BBox) XXX_Size() int {
	return xxx_messageInfo_BBox.Size(m)
}
func (m *BBox) XXX_DiscardUnknown() {
	xxx_messageInfo_BBox.DiscardUnknown(m)
}

var xxx_messageInfo_BBox proto.InternalMessageInfo

func (m *BBox) GetLeftTop() *Point {
	if m != nil {
		return m.LeftTop
	}
	return nil
}

func (m *BBox) GetRightBottom() *Point {
	if m != nil {
		return m.RightBottom
	}
	return nil
}

func (m *BBox) GetConfidence() float32 {
	if m != nil {
		return m.Confidence
	}
	return 0
}

type Mask struct {
	Segms                []*Point `protobuf:"bytes,1,rep,name=segms,proto3" json:"segms,omitempty"`
	Confidence           float32  `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Mask) Reset()         { *m = Mask{} }
func (m *Mask) String() string { return proto.CompactTextString(m) }
func (*Mask) ProtoMessage()    {}
func (*Mask) Descriptor() ([]byte, []int) {
	return fileDescriptor_infer_server_0eb42ce3bc0a4c21, []int{6}
}
func (m *Mask) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mask.Unmarshal(m, b)
}
func (m *Mask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mask.Marshal(b, m, deterministic)
}
func (dst *Mask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mask.Merge(dst, src)
}
func (m *Mask) XXX_Size() int {
	return xxx_messageInfo_Mask.Size(m)
}
func (m *Mask) XXX_DiscardUnknown() {
	xxx_messageInfo_Mask.DiscardUnknown(m)
}

var xxx_messageInfo_Mask proto.InternalMessageInfo

func (m *Mask) GetSegms() []*Point {
	if m != nil {
		return m.Segms
	}
	return nil
}

func (m *Mask) GetConfidence() float32 {
	if m != nil {
		return m.Confidence
	}
	return 0
}

type KeyPoints struct {
	Points               []*Point `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	Visibility           []bool   `protobuf:"varint,2,rep,packed,name=visibility,proto3" json:"visibility,omitempty"`
	Confidence           float32  `protobuf:"fixed32,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyPoints) Reset()         { *m = KeyPoints{} }
func (m *KeyPoints) String() string { return proto.CompactTextString(m) }
func (*KeyPoints) ProtoMessage()    {}
func (*KeyPoints) Descriptor() ([]byte, []int) {
	return fileDescriptor_infer_server_0eb42ce3bc0a4c21, []int{7}
}
func (m *KeyPoints) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyPoints.Unmarshal(m, b)
}
func (m *KeyPoints) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyPoints.Marshal(b, m, deterministic)
}
func (dst *KeyPoints) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyPoints.Merge(dst, src)
}
func (m *KeyPoints) XXX_Size() int {
	return xxx_messageInfo_KeyPoints.Size(m)
}
func (m *KeyPoints) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyPoints.DiscardUnknown(m)
}

var xxx_messageInfo_KeyPoints proto.InternalMessageInfo

func (m *KeyPoints) GetPoints() []*Point {
	if m != nil {
		return m.Points
	}
	return nil
}

func (m *KeyPoints) GetVisibility() []bool {
	if m != nil {
		return m.Visibility
	}
	return nil
}

func (m *KeyPoints) GetConfidence() float32 {
	if m != nil {
		return m.Confidence
	}
	return 0
}

type Detection struct {
	Bbox                 *BBox             `protobuf:"bytes,1,opt,name=bbox,proto3" json:"bbox,omitempty"`
	Mask                 *Mask             `protobuf:"bytes,2,opt,name=mask,proto3" json:"mask,omitempty"`
	Keypoints            *KeyPoints        `protobuf:"bytes,3,opt,name=keypoints,proto3" json:"keypoints,omitempty"`
	Cls                  []*Classification `protobuf:"bytes,4,rep,name=cls,proto3" json:"cls,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Detection) Reset()         { *m = Detection{} }
func (m *Detection) String() string { return proto.CompactTextString(m) }
func (*Detection) ProtoMessage()    {}
func (*Detection) Descriptor() ([]byte, []int) {
	return fileDescriptor_infer_server_0eb42ce3bc0a4c21, []int{8}
}
func (m *Detection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Detection.Unmarshal(m, b)
}
func (m *Detection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Detection.Marshal(b, m, deterministic)
}
func (dst *Detection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Detection.Merge(dst, src)
}
func (m *Detection) XXX_Size() int {
	return xxx_messageInfo_Detection.Size(m)
}
func (m *Detection) XXX_DiscardUnknown() {
	xxx_messageInfo_Detection.DiscardUnknown(m)
}

var xxx_messageInfo_Detection proto.InternalMessageInfo

func (m *Detection) GetBbox() *BBox {
	if m != nil {
		return m.Bbox
	}
	return nil
}

func (m *Detection) GetMask() *Mask {
	if m != nil {
		return m.Mask
	}
	return nil
}

func (m *Detection) GetKeypoints() *KeyPoints {
	if m != nil {
		return m.Keypoints
	}
	return nil
}

func (m *Detection) GetCls() []*Classification {
	if m != nil {
		return m.Cls
	}
	return nil
}

type DetectResponse struct {
	Context *Context `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	// Types that are valid to be assigned to ErrNoOneof:
	//	*DetectResponse_ErrNo
	ErrNoOneof isDetectResponse_ErrNoOneof `protobuf_oneof:"err_no_oneof"`
	// Types that are valid to be assigned to ErrMsgOneof:
	//	*DetectResponse_ErrMsg
	ErrMsgOneof          isDetectResponse_ErrMsgOneof `protobuf_oneof:"err_msg_oneof"`
	RequestId            string                       `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Detections           []*Detection                 `protobuf:"bytes,5,rep,name=detections,proto3" json:"detections,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *DetectResponse) Reset()         { *m = DetectResponse{} }
func (m *DetectResponse) String() string { return proto.CompactTextString(m) }
func (*DetectResponse) ProtoMessage()    {}
func (*DetectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_infer_server_0eb42ce3bc0a4c21, []int{9}
}
func (m *DetectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetectResponse.Unmarshal(m, b)
}
func (m *DetectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetectResponse.Marshal(b, m, deterministic)
}
func (dst *DetectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetectResponse.Merge(dst, src)
}
func (m *DetectResponse) XXX_Size() int {
	return xxx_messageInfo_DetectResponse.Size(m)
}
func (m *DetectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DetectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DetectResponse proto.InternalMessageInfo

func (m *DetectResponse) GetContext() *Context {
	if m != nil {
		return m.Context
	}
	return nil
}

type isDetectResponse_ErrNoOneof interface {
	isDetectResponse_ErrNoOneof()
}

type DetectResponse_ErrNo struct {
	ErrNo int32 `protobuf:"varint,2,opt,name=err_no,json=errNo,proto3,oneof"`
}

func (*DetectResponse_ErrNo) isDetectResponse_ErrNoOneof() {}

func (m *DetectResponse) GetErrNoOneof() isDetectResponse_ErrNoOneof {
	if m != nil {
		return m.ErrNoOneof
	}
	return nil
}

func (m *DetectResponse) GetErrNo() int32 {
	if x, ok := m.GetErrNoOneof().(*DetectResponse_ErrNo); ok {
		return x.ErrNo
	}
	return 0
}

type isDetectResponse_ErrMsgOneof interface {
	isDetectResponse_ErrMsgOneof()
}

type DetectResponse_ErrMsg struct {
	ErrMsg string `protobuf:"bytes,3,opt,name=err_msg,json=errMsg,proto3,oneof"`
}

func (*DetectResponse_ErrMsg) isDetectResponse_ErrMsgOneof() {}

func (m *DetectResponse) GetErrMsgOneof() isDetectResponse_ErrMsgOneof {
	if m != nil {
		return m.ErrMsgOneof
	}
	return nil
}

func (m *DetectResponse) GetErrMsg() string {
	if x, ok := m.GetErrMsgOneof().(*DetectResponse_ErrMsg); ok {
		return x.ErrMsg
	}
	return ""
}

func (m *DetectResponse) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *DetectResponse) GetDetections() []*Detection {
	if m != nil {
		return m.Detections
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*DetectResponse) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _DetectResponse_OneofMarshaler, _DetectResponse_OneofUnmarshaler, _DetectResponse_OneofSizer, []interface{}{
		(*DetectResponse_ErrNo)(nil),
		(*DetectResponse_ErrMsg)(nil),
	}
}

func _DetectResponse_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*DetectResponse)
	// err_no_oneof
	switch x := m.ErrNoOneof.(type) {
	case *DetectResponse_ErrNo:
		b.EncodeVarint(2<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.ErrNo))
	case nil:
	default:
		return fmt.Errorf("DetectResponse.ErrNoOneof has unexpected type %T", x)
	}
	// err_msg_oneof
	switch x := m.ErrMsgOneof.(type) {
	case *DetectResponse_ErrMsg:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.ErrMsg)
	case nil:
	default:
		return fmt.Errorf("DetectResponse.ErrMsgOneof has unexpected type %T", x)
	}
	return nil
}

func _DetectResponse_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*DetectResponse)
	switch tag {
	case 2: // err_no_oneof.err_no
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.ErrNoOneof = &DetectResponse_ErrNo{int32(x)}
		return true, err
	case 3: // err_msg_oneof.err_msg
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.ErrMsgOneof = &DetectResponse_ErrMsg{x}
		return true, err
	default:
		return false, nil
	}
}

func _DetectResponse_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*DetectResponse)
	// err_no_oneof
	switch x := m.ErrNoOneof.(type) {
	case *DetectResponse_ErrNo:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.ErrNo))
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	// err_msg_oneof
	switch x := m.ErrMsgOneof.(type) {
	case *DetectResponse_ErrMsg:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.ErrMsg)))
		n += len(x.ErrMsg)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*Point)(nil), "detectron.infer.Point")
	proto.RegisterType((*Context)(nil), "detectron.infer.Context")
	proto.RegisterMapType((map[string]string)(nil), "detectron.infer.Context.OptionParamsEntry")
	proto.RegisterMapType((map[string]string)(nil), "detectron.infer.Context.UserDataEntry")
	proto.RegisterType((*Classification)(nil), "detectron.infer.Classification")
	proto.RegisterType((*RequestData)(nil), "detectron.infer.RequestData")
	proto.RegisterType((*DetectRequest)(nil), "detectron.infer.DetectRequest")
	proto.RegisterType((*BBox)(nil), "detectron.infer.BBox")
	proto.RegisterType((*Mask)(nil), "detectron.infer.Mask")
	proto.RegisterType((*KeyPoints)(nil), "detectron.infer.KeyPoints")
	proto.RegisterType((*Detection)(nil), "detectron.infer.Detection")
	proto.RegisterType((*DetectResponse)(nil), "detectron.infer.DetectResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DetectronServiceClient is the client API for DetectronService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DetectronServiceClient interface {
	Detect(ctx context.Context, in *DetectRequest, opts ...grpc.CallOption) (*DetectResponse, error)
}

type detectronServiceClient struct {
	cc *grpc.ClientConn
}

func NewDetectronServiceClient(cc *grpc.ClientConn) DetectronServiceClient {
	return &detectronServiceClient{cc}
}

func (c *detectronServiceClient) Detect(ctx context.Context, in *DetectRequest, opts ...grpc.CallOption) (*DetectResponse, error) {
	out := new(DetectResponse)
	err := c.cc.Invoke(ctx, "/detectron.infer.DetectronService/Detect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DetectronServiceServer is the server API for DetectronService service.
type DetectronServiceServer interface {
	Detect(context.Context, *DetectRequest) (*DetectResponse, error)
}

func RegisterDetectronServiceServer(s *grpc.Server, srv DetectronServiceServer) {
	s.RegisterService(&_DetectronService_serviceDesc, srv)
}

func _DetectronService_Detect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DetectronServiceServer).Detect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/detectron.infer.DetectronService/Detect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DetectronServiceServer).Detect(ctx, req.(*DetectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DetectronService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "detectron.infer.DetectronService",
	HandlerType: (*DetectronServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Detect",
			Handler:    _DetectronService_Detect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/infer_server.proto",
}

func init() {
	proto.RegisterFile("proto/infer_server.proto", fileDescriptor_infer_server_0eb42ce3bc0a4c21)
}

var fileDescriptor_infer_server_0eb42ce3bc0a4c21 = []byte{
	// 667 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xdf, 0x6e, 0xd3, 0x3e,
	0x14, 0xc7, 0x97, 0xfe, 0x5d, 0x4e, 0xdb, 0x6d, 0x3f, 0xeb, 0xc7, 0x08, 0x15, 0x6c, 0x53, 0x90,
	0xd0, 0x40, 0xa8, 0xb0, 0x82, 0x60, 0x8c, 0x0b, 0xa4, 0x6e, 0xa0, 0xa1, 0x69, 0x6c, 0x32, 0xe3,
	0x3a, 0x4a, 0x53, 0xb7, 0x44, 0x6d, 0xe3, 0x60, 0xbb, 0xa5, 0x11, 0xaf, 0xc1, 0x2d, 0xaf, 0xc4,
	0xd3, 0xf0, 0x00, 0xc8, 0xc7, 0xee, 0xe8, 0x16, 0x55, 0x13, 0xdc, 0xe5, 0x1c, 0x7f, 0xce, 0xf7,
	0xd8, 0x5f, 0x1f, 0x07, 0xbc, 0x54, 0x70, 0xc5, 0x9f, 0xc4, 0x49, 0x9f, 0x89, 0x40, 0x32, 0x31,
	0x65, 0xa2, 0x85, 0x29, 0xb2, 0xde, 0x63, 0x8a, 0x45, 0x4a, 0xf0, 0xa4, 0x85, 0xab, 0xfe, 0x7d,
	0x28, 0x9f, 0xf3, 0x38, 0x51, 0xa4, 0x0e, 0xce, 0xcc, 0x73, 0x76, 0x9c, 0xdd, 0x32, 0x75, 0x66,
	0x3a, 0xca, 0xbc, 0x82, 0x89, 0x32, 0xff, 0x47, 0x01, 0xaa, 0x87, 0x3c, 0x51, 0x6c, 0xa6, 0xc8,
	0x21, 0xb8, 0x13, 0xc9, 0x44, 0xd0, 0x0b, 0x55, 0xe8, 0x39, 0x3b, 0xc5, 0xdd, 0x5a, 0xfb, 0x41,
	0xeb, 0x9a, 0x6a, 0xcb, 0xc2, 0xad, 0x4f, 0x92, 0x89, 0xa3, 0x50, 0x85, 0x6f, 0x13, 0x25, 0x32,
	0xba, 0x3a, 0xb1, 0x21, 0x39, 0x83, 0x06, 0x4f, 0x55, 0xcc, 0x93, 0x20, 0x0d, 0x45, 0x38, 0x96,
	0x5e, 0x01, 0x85, 0x1e, 0x2d, 0x15, 0x3a, 0x43, 0xfa, 0x1c, 0x61, 0x23, 0x56, 0xe7, 0x0b, 0xa9,
	0xe6, 0x6b, 0x68, 0x5c, 0xe9, 0x45, 0x36, 0xa0, 0x38, 0x64, 0x19, 0x1e, 0xc8, 0xa5, 0xfa, 0x93,
	0xfc, 0x0f, 0xe5, 0x69, 0x38, 0x9a, 0x30, 0x3c, 0x96, 0x4b, 0x4d, 0x70, 0x50, 0xd8, 0x77, 0x9a,
	0x6f, 0xe0, 0xbf, 0x9c, 0xfe, 0xdf, 0x08, 0xf8, 0xef, 0x60, 0xed, 0x70, 0x14, 0x4a, 0x19, 0xf7,
	0xe3, 0x28, 0xd4, 0x42, 0x9a, 0x8d, 0x74, 0xc6, 0xd6, 0x9b, 0x80, 0x6c, 0x01, 0x44, 0x3c, 0xe9,
	0xc7, 0x3d, 0x96, 0x44, 0x46, 0xa6, 0x40, 0x17, 0x32, 0xfe, 0x4b, 0xa8, 0x51, 0xf6, 0x65, 0xc2,
	0xa4, 0x42, 0x97, 0x36, 0xa1, 0xd2, 0x0d, 0x25, 0x7b, 0xf1, 0xdc, 0xaa, 0xd8, 0x48, 0x6f, 0x4d,
	0x84, 0x5f, 0xb1, 0xbe, 0x4e, 0xf5, 0xa7, 0x3f, 0x81, 0xc6, 0x11, 0x3a, 0x67, 0xcb, 0x49, 0x1b,
	0xaa, 0x91, 0xb1, 0x0e, 0x6b, 0x6b, 0x6d, 0x6f, 0x99, 0xb5, 0x74, 0x0e, 0x92, 0xa7, 0x50, 0xc2,
	0x4b, 0x2d, 0x60, 0xc1, 0xdd, 0x5c, 0xc1, 0xc2, 0xd6, 0x28, 0x92, 0xfe, 0x77, 0x07, 0x4a, 0x9d,
	0x0e, 0x9f, 0x91, 0x3d, 0x58, 0x1d, 0xb1, 0xbe, 0x0a, 0x14, 0x4f, 0x6d, 0xbf, 0xcd, 0x5c, 0x39,
	0x8e, 0x19, 0xad, 0x6a, 0xee, 0x82, 0xa7, 0xe4, 0x15, 0xd4, 0x45, 0x3c, 0xf8, 0xac, 0x82, 0x2e,
	0x57, 0x8a, 0x8f, 0x6d, 0xd7, 0x65, 0x65, 0x35, 0x64, 0x3b, 0x88, 0x5e, 0xb3, 0xb1, 0x9c, 0xb3,
	0xf1, 0x02, 0x4a, 0xa7, 0xa1, 0x1c, 0x92, 0xc7, 0x50, 0x96, 0x6c, 0x30, 0x96, 0x76, 0x4c, 0x97,
	0x69, 0x1b, 0xe8, 0xc6, 0xcb, 0xf9, 0x06, 0xee, 0x09, 0xcb, 0xb0, 0x44, 0x92, 0x16, 0x54, 0x52,
	0xfc, 0xba, 0x41, 0xdb, 0x52, 0x5a, 0x7c, 0x1a, 0xcb, 0xb8, 0x1b, 0x8f, 0x62, 0x95, 0xe1, 0xb4,
	0xaf, 0xd2, 0x85, 0xcc, 0xb5, 0xe6, 0xc5, 0x5c, 0xf3, 0x9f, 0x0e, 0xb8, 0xe6, 0x86, 0xf5, 0x74,
	0x3d, 0x84, 0x52, 0xb7, 0xcb, 0x67, 0xd6, 0xea, 0x5b, 0xb9, 0xde, 0xfa, 0x4e, 0x28, 0x22, 0x1a,
	0x1d, 0x87, 0x72, 0x68, 0xed, 0xcd, 0xa3, 0xda, 0x28, 0x8a, 0x08, 0xd9, 0x07, 0x77, 0xc8, 0x32,
	0x7b, 0xac, 0x22, 0xf2, 0xcd, 0x1c, 0x7f, 0x69, 0x01, 0xfd, 0x03, 0x93, 0x3d, 0x28, 0x46, 0x23,
	0xe9, 0x95, 0xd0, 0x8a, 0xed, 0xfc, 0xa4, 0x5d, 0x79, 0x1b, 0x54, 0xb3, 0xfe, 0x2f, 0x07, 0xd6,
	0xe6, 0x23, 0x2b, 0x53, 0x9e, 0x48, 0xf6, 0x4f, 0x33, 0x7b, 0x1b, 0x2a, 0x4c, 0x88, 0x20, 0xe1,
	0xe6, 0x67, 0x75, 0xbc, 0x42, 0xcb, 0x4c, 0x88, 0x0f, 0x9c, 0xdc, 0x81, 0xaa, 0x5e, 0x18, 0xcb,
	0x01, 0x1e, 0xc5, 0x3d, 0x76, 0xa8, 0x26, 0x4f, 0xe5, 0x80, 0xdc, 0x03, 0x10, 0x66, 0x94, 0x83,
	0xb8, 0xe7, 0x95, 0xf0, 0x69, 0xb9, 0x36, 0xf3, 0xbe, 0x47, 0x0e, 0x00, 0x7a, 0x73, 0xa7, 0xa5,
	0x57, 0xc6, 0x33, 0xe5, 0x7d, 0xb8, 0xbc, 0x0c, 0xba, 0x40, 0x77, 0xd6, 0xa0, 0x6e, 0xb6, 0x13,
	0xf0, 0x84, 0xf1, 0x7e, 0x67, 0x1d, 0x1a, 0x76, 0x17, 0x26, 0xd1, 0x0e, 0x60, 0xe3, 0x68, 0xae,
	0xf4, 0x91, 0x89, 0x69, 0x1c, 0x31, 0x72, 0x02, 0x15, 0x93, 0x23, 0x5b, 0x4b, 0xda, 0xd8, 0x97,
	0xd7, 0xdc, 0x5e, 0xba, 0x6e, 0x2c, 0xf4, 0x57, 0xba, 0x15, 0xfc, 0xcf, 0x3f, 0xfb, 0x1d, 0x00,
	0x00, 0xff, 0xff, 0xf6, 0x2a, 0x9e, 0x2a, 0x03, 0x06, 0x00, 0x00,
}
